import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const DEFAULT_API_BASE = process.env.CLAWZ_API_BASE?.trim() || "https://api.santaclawz.ai";
const DEFAULT_SITE_BASE = process.env.CLAWZ_SITE_BASE?.trim() || "https://santaclawz.ai";
const FACILITATOR_SETUP_GUIDE_URL =
  "https://github.com/Evan-k-global/santa_clawz-private_agents/blob/main/docs/host-x402-facilitator-on-render.md";
const VALID_TRUST_MODES = new Set(["fast", "private", "verified", "team-governed"]);
const VALID_PROVING_LOCATIONS = new Set(["client", "sovereign-rollup"]);
const VALID_PAYMENT_RAILS = new Set(["base-usdc", "ethereum-usdc", "zeko-native"]);
const VALID_PRICING_MODES = new Set(["fixed-exact", "capped-exact", "quote-required", "agent-negotiated"]);
const VALID_SETTLEMENT_TRIGGERS = new Set(["upfront", "on-proof"]);
const VALID_SOCIAL_ANCHOR_MODES = new Set(["shared-batched", "priority-self-funded"]);

function printUsage() {
  console.error(`Usage:
  pnpm register:agent -- \\
    --agent-name "Northstar Research" \\
    --headline "Private research and verifiable delivery." \\
    --openclaw-url "https://agent.example.com" \\
    [--represented-principal "Northstar Labs"] \\
    [--zeko-payout-address "B62..."] \\
    [--base-payout-address "0x..."] \\
    [--ethereum-payout-address "0x..."] \\
    [--payments-enabled] \\
    [--base-facilitator-url "https://your-base-facilitator.onrender.com"] \\
    [--ethereum-facilitator-url "https://your-ethereum-facilitator.onrender.com"] \\
    [--default-rail "base-usdc"] \\
    [--pricing-mode fixed-exact] \\
    [--fixed-price-usd "0.05"] \\
    [--quote-url "https://agent.example.com/payments"] \\
    [--payment-notes "Custom quotes available for larger jobs."] \\
    [--anchor-mode shared-batched] \\
    [--trust-mode private] \\
    [--proving-location client] \\
    [--api-base https://api.santaclawz.ai] \\
    [--site-base https://santaclawz.ai] \\
    [--write-env .env.santaclawz] \\
    [--write-challenge .well-known/santaclawz-agent-challenge.json] \\
    [--json]

Advanced:
    [--supported-rails "base-usdc,ethereum-usdc"] \\
    [--max-price-usd "0.25"] \\
    [--settlement-trigger upfront]
`);
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === "--") {
      continue;
    }
    if (!token.startsWith("--")) {
      continue;
    }

    const key = token.slice(2);
    if (key === "json" || key === "help") {
      args[key] = true;
      continue;
    }

    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      throw new Error(`Missing value for --${key}`);
    }

    args[key] = value;
    index += 1;
  }
  return args;
}

function normalizeBaseUrl(value) {
  return value.endsWith("/") ? value.slice(0, -1) : value;
}

function envQuote(value) {
  return `"${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$")
    .replace(/`/g, "\\`")}"`;
}

function writePrivateFile(filePath, contents) {
  const resolvedPath = path.resolve(filePath);
  mkdirSync(path.dirname(resolvedPath), { recursive: true });
  writeFileSync(resolvedPath, contents, { mode: 0o600 });
  return resolvedPath;
}

function buildAgentEnvFile(result, issuedAdminKey) {
  const lines = [
    "# Generated by SantaClawz agent registration.",
    "# Keep this file private. It contains the SantaClawz agent admin key.",
    `CLAWZ_API_BASE=${envQuote(result.apiBase)}`,
    `CLAWZ_SITE_BASE=${envQuote(result.siteBase)}`,
    `CLAWZ_AGENT_ID=${envQuote(result.agentId)}`,
    `CLAWZ_AGENT_SESSION_ID=${envQuote(result.sessionId)}`,
    `CLAWZ_AGENT_ADMIN_KEY=${envQuote(issuedAdminKey ?? "")}`,
    `CLAWZ_AGENT_PUBLIC_URL=${envQuote(result.publicAgentUrl)}`,
    `CLAWZ_AGENT_DISCOVERY_URL=${envQuote(result.discoveryUrl)}`,
    `CLAWZ_AGENT_VERIFY_URL=${envQuote(result.verifyUrl)}`
  ];
  if (result.ownershipChallenge?.challengeUrl) {
    lines.push(`CLAWZ_AGENT_OWNERSHIP_CHALLENGE_URL=${envQuote(result.ownershipChallenge.challengeUrl)}`);
  }
  if (result.networkId) {
    lines.push(`CLAWZ_ZEKO_NETWORK_ID=${envQuote(result.networkId)}`);
  }
  return `${lines.join("\n")}\n`;
}

const args = parseArgs(process.argv.slice(2));

if (args.help) {
  printUsage();
  process.exit(0);
}

const agentName = typeof args["agent-name"] === "string" ? args["agent-name"].trim() : "";
const headline = typeof args.headline === "string" ? args.headline.trim() : "";
const openClawUrl = typeof args["openclaw-url"] === "string" ? args["openclaw-url"].trim() : "";
const representedPrincipal =
  typeof args["represented-principal"] === "string" ? args["represented-principal"].trim() : undefined;
const payoutWallets = {
  ...(typeof args["zeko-payout-address"] === "string" && args["zeko-payout-address"].trim().length > 0
    ? { zeko: args["zeko-payout-address"].trim() }
    : {}),
  ...(typeof args["base-payout-address"] === "string" && args["base-payout-address"].trim().length > 0
    ? { base: args["base-payout-address"].trim() }
    : {}),
  ...(typeof args["ethereum-payout-address"] === "string" && args["ethereum-payout-address"].trim().length > 0
    ? { ethereum: args["ethereum-payout-address"].trim() }
    : {})
};
const derivedSupportedRails = ["base-usdc"];
const supportedRails =
  typeof args["supported-rails"] === "string"
    ? args["supported-rails"]
        .split(",")
        .map((value) => value.trim())
        .filter((value) => value.length > 0)
    : derivedSupportedRails.length > 0
      ? derivedSupportedRails
      : ["base-usdc"];
const paymentProfile = {
  enabled: Boolean(args["payments-enabled"]),
  supportedRails,
  ...(typeof args["base-facilitator-url"] === "string"
    ? { baseFacilitatorUrl: args["base-facilitator-url"].trim() }
    : {}),
  ...(typeof args["ethereum-facilitator-url"] === "string"
    ? { ethereumFacilitatorUrl: args["ethereum-facilitator-url"].trim() }
    : {}),
  ...(typeof args["default-rail"] === "string" ? { defaultRail: args["default-rail"].trim() } : {}),
  pricingMode: typeof args["pricing-mode"] === "string" ? args["pricing-mode"].trim() : "fixed-exact",
  ...(typeof args["fixed-price-usd"] === "string" ? { fixedAmountUsd: args["fixed-price-usd"].trim() } : {}),
  ...(typeof args["max-price-usd"] === "string" ? { maxAmountUsd: args["max-price-usd"].trim() } : {}),
  ...(typeof args["quote-url"] === "string" ? { quoteUrl: args["quote-url"].trim() } : {}),
  settlementTrigger:
    typeof args["settlement-trigger"] === "string" ? args["settlement-trigger"].trim() : "upfront",
  ...(typeof args["payment-notes"] === "string" ? { paymentNotes: args["payment-notes"].trim() } : {})
};
const trustModeId = typeof args["trust-mode"] === "string" ? args["trust-mode"].trim() : "private";
const socialAnchorPolicy = {
  mode: typeof args["anchor-mode"] === "string" ? args["anchor-mode"].trim() : "shared-batched"
};
const preferredProvingLocation =
  typeof args["proving-location"] === "string" ? args["proving-location"].trim() : undefined;
const apiBase = normalizeBaseUrl(typeof args["api-base"] === "string" ? args["api-base"].trim() : DEFAULT_API_BASE);
const siteBase = normalizeBaseUrl(typeof args["site-base"] === "string" ? args["site-base"].trim() : DEFAULT_SITE_BASE);
const writeEnvPath = typeof args["write-env"] === "string" ? args["write-env"].trim() : "";
const writeChallengePath = typeof args["write-challenge"] === "string" ? args["write-challenge"].trim() : "";

if (!agentName || !headline || !openClawUrl) {
  printUsage();
  throw new Error("agent-name, headline, and openclaw-url are required.");
}

if (!VALID_TRUST_MODES.has(trustModeId)) {
  throw new Error(`Unsupported trust mode: ${trustModeId}`);
}

if (preferredProvingLocation && !VALID_PROVING_LOCATIONS.has(preferredProvingLocation)) {
  throw new Error(`Unsupported proving location: ${preferredProvingLocation}`);
}

if (supportedRails.some((rail) => !VALID_PAYMENT_RAILS.has(rail))) {
  throw new Error(`Unsupported payment rail. Supported rails: ${Array.from(VALID_PAYMENT_RAILS).join(", ")}`);
}

if (
  typeof paymentProfile.defaultRail === "string" &&
  (!VALID_PAYMENT_RAILS.has(paymentProfile.defaultRail) || !supportedRails.includes(paymentProfile.defaultRail))
) {
  throw new Error("default-rail must be one of the supported rails.");
}

if (!VALID_PRICING_MODES.has(paymentProfile.pricingMode)) {
  throw new Error(`Unsupported pricing mode: ${paymentProfile.pricingMode}`);
}

if (!VALID_SETTLEMENT_TRIGGERS.has(paymentProfile.settlementTrigger)) {
  throw new Error(`Unsupported settlement trigger: ${paymentProfile.settlementTrigger}`);
}

if (!VALID_SOCIAL_ANCHOR_MODES.has(socialAnchorPolicy.mode)) {
  throw new Error(`Unsupported anchor mode: ${socialAnchorPolicy.mode}`);
}

const response = await fetch(`${apiBase}/api/console/register`, {
  method: "POST",
  headers: {
    "content-type": "application/json"
  },
  body: JSON.stringify({
    agentName,
    headline,
    openClawUrl,
    ...(Object.keys(payoutWallets).length > 0 ? { payoutWallets } : {}),
    paymentProfile,
    socialAnchorPolicy,
    ...(representedPrincipal ? { representedPrincipal } : {}),
    trustModeId,
    ...(preferredProvingLocation ? { preferredProvingLocation } : {})
  })
});

if (!response.ok) {
  const errorPayload = await response.json().catch(() => null);
  throw new Error(errorPayload?.error ?? `Registration failed with status ${response.status}`);
}

const state = await response.json();
const sessionId = state.session?.sessionId;
const agentId = state.agentId;

if (typeof sessionId !== "string" || typeof agentId !== "string") {
  throw new Error("Registration succeeded but response was missing sessionId or agentId.");
}

const issuedAdminKey =
  typeof state.adminAccess?.issuedAdminKey === "string" ? state.adminAccess.issuedAdminKey : undefined;
if (!issuedAdminKey) {
  throw new Error("Registration succeeded but response was missing the SantaClawz agent admin key.");
}
let ownershipChallenge = null;

try {
  const challengeResponse = await fetch(`${apiBase}/api/ownership/challenge`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      ...(issuedAdminKey ? { "x-clawz-admin-key": issuedAdminKey } : {})
    },
    body: JSON.stringify({
      sessionId,
      agentId
    })
  });

  if (challengeResponse.ok) {
    const challengePayload = await challengeResponse.json();
    ownershipChallenge = challengePayload?.issuedOwnershipChallenge ?? null;
  }
} catch (_error) {
  ownershipChallenge = null;
}

const result = {
  apiBase,
  siteBase,
  agentId,
  sessionId,
  ...(issuedAdminKey ? { adminKey: issuedAdminKey } : {}),
  networkId: state.deployment?.networkId,
  trustModeId: state.wallet?.trustModeId,
  provingLocation: state.profile?.preferredProvingLocation,
  payoutAddressConfigured: state.payoutAddressConfigured,
  paymentsEnabled: state.paymentsEnabled,
  paymentProfileReady: state.paymentProfileReady,
  paidJobsEnabled: state.paidJobsEnabled,
  publicAgentUrl: `${siteBase}/explore/${encodeURIComponent(agentId)}`,
  discoveryUrl: `${apiBase}/.well-known/agent-interop.json?sessionId=${encodeURIComponent(sessionId)}`,
  verifyUrl: `${apiBase}/api/interop/verify?sessionId=${encodeURIComponent(sessionId)}`,
  ...(ownershipChallenge ? { ownershipChallenge } : {}),
  profile: state.profile
};

const writtenFiles = [];
if (writeEnvPath) {
  writtenFiles.push({
    label: "agent env",
    path: writePrivateFile(writeEnvPath, buildAgentEnvFile(result, issuedAdminKey))
  });
}
if (writeChallengePath && ownershipChallenge?.challengeResponseJson) {
  writtenFiles.push({
    label: "ownership challenge",
    path: writePrivateFile(writeChallengePath, `${ownershipChallenge.challengeResponseJson}\n`)
  });
}

if (writtenFiles.length > 0) {
  result.writtenFiles = writtenFiles;
}

if (args.json) {
  console.log(JSON.stringify(result, null, 2));
} else {
  console.log(`Registered ${agentName}`);
  console.log(`Agent ID: ${result.agentId}`);
  console.log(`Session ID: ${result.sessionId}`);
  console.log(`Network: ${result.networkId}`);
  console.log(`Public URL: ${result.publicAgentUrl}`);
  console.log(`Discovery URL: ${result.discoveryUrl}`);
  console.log(`Verify URL: ${result.verifyUrl}`);
  if (issuedAdminKey) {
    console.log(`Admin key: ${issuedAdminKey}`);
  }
  for (const file of writtenFiles) {
    console.log(`Wrote ${file.label}: ${file.path}`);
  }
  console.log(`Payout wallets configured: ${result.payoutAddressConfigured ? "yes" : "no"}`);
  console.log(`Payments enabled: ${result.paymentsEnabled ? "yes" : "no"}`);
  console.log(`Payment profile ready: ${result.paymentProfileReady ? "yes" : "no"}`);
  console.log(`Payouts live: ${result.paidJobsEnabled ? "yes" : "no"}`);
  if (ownershipChallenge) {
    console.log("");
    console.log("Ownership challenge issued");
    console.log(`Serve this at: ${ownershipChallenge.challengeUrl}`);
    console.log(ownershipChallenge.challengeResponseJson);
    console.log("");
    console.log("Then verify control:");
    console.log(
      `curl -X POST ${apiBase}/api/ownership/verify -H 'content-type: application/json' -H 'x-clawz-admin-key: ${issuedAdminKey ?? "sck_..."}' -d '${JSON.stringify({ sessionId, agentId })}'`
    );
    if (writeChallengePath) {
      console.log("");
      console.log(`Ownership challenge file written to ${path.resolve(writeChallengePath)}.`);
    }
  }
  if (result.paymentsEnabled && !result.paidJobsEnabled) {
    console.log("");
    console.log("Next step: host your x402 facilitator and paste its HTTPS URL back into SantaClawz.");
    console.log(`Guide: ${FACILITATOR_SETUP_GUIDE_URL}`);
    console.log("Once it is live, re-run registration with --base-facilitator-url or --ethereum-facilitator-url.");
  }
}
