#!/usr/bin/env node
import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, appendFileSync } from "node:fs";
import { createServer } from "node:http";
import path from "node:path";

const DEFAULT_HOST = "127.0.0.1";
const DEFAULT_PORT = 8797;
const DEFAULT_MAX_BODY_BYTES = 64 * 1024;
const DEFAULT_MAX_TIMESTAMP_AGE_MS = 5 * 60 * 1000;
const DEFAULT_REPLAY_TTL_MS = 10 * 60 * 1000;
const DEFAULT_RATE_LIMIT_PER_MINUTE = 60;
const DEFAULT_QUOTE_AMOUNT_USD = "0.20";
const CHALLENGE_PATH = "/.well-known/santaclawz-agent-challenge.json";

const replayCache = new Map();
const rateLimitBuckets = new Map();

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === "--") {
      continue;
    }
    if (!token.startsWith("--")) {
      continue;
    }
    const key = token.slice(2);
    if (key === "help") {
      args[key] = true;
      continue;
    }
    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      throw new Error(`Missing value for --${key}`);
    }
    args[key] = value;
    index += 1;
  }
  return args;
}

function printUsage() {
  console.error(`Usage:
  node starters/openclaw-public-hire-ingress/server.mjs \\
    [--agent-env-file .env.santaclawz] \\
    [--challenge-file .well-known/santaclawz-agent-challenge.json] \\
    [--host 127.0.0.1] \\
    [--port 8797]

Important env vars:
  CLAWZ_AGENT_INGRESS_TOKEN      Bearer token generated by SantaClawz enrollment.
  CLAWZ_AGENT_SIGNING_SECRET     HMAC key generated by SantaClawz enrollment.
  CLAWZ_AGENT_QUOTE_AMOUNT_USD   Optional exact quote amount returned for quote intake.
  OPENCLAW_INTERNAL_HIRE_URL     Optional private runtime URL for paid execution.
`);
}

function unquoteEnvValue(value) {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function readEnvFile(filePath) {
  if (!filePath || !existsSync(filePath)) {
    return {};
  }
  const env = {};
  for (const rawLine of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const separatorIndex = line.indexOf("=");
    if (separatorIndex <= 0) {
      continue;
    }
    env[line.slice(0, separatorIndex).trim()] = unquoteEnvValue(line.slice(separatorIndex + 1));
  }
  return env;
}

function parsePositiveInteger(value, fallback) {
  const parsed = Number.parseInt(String(value ?? ""), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function resolvePath(value, fallback) {
  const candidate = String(value ?? fallback ?? "").trim();
  return candidate ? path.resolve(candidate) : "";
}

function loadConfig(args) {
  const envFile = resolvePath(args["agent-env-file"] ?? args["env-file"] ?? process.env.CLAWZ_AGENT_ENV_FILE, "");
  const fileEnv = readEnvFile(envFile);
  const env = {
    ...process.env,
    ...fileEnv
  };
  const challengeFile = resolvePath(
    args["challenge-file"] ?? env.CLAWZ_AGENT_OWNERSHIP_CHALLENGE_FILE,
    ".well-known/santaclawz-agent-challenge.json"
  );
  return {
    envFile,
    challengeFile,
    ingressToken: String(env.CLAWZ_AGENT_INGRESS_TOKEN ?? "").trim(),
    signingSecret: String(env.CLAWZ_AGENT_SIGNING_SECRET ?? "").trim(),
    quoteAmountUsd: String(
      env.CLAWZ_AGENT_QUOTE_AMOUNT_USD ??
        env.CLAWZ_AGENT_REFERENCE_PRICE_USD ??
        DEFAULT_QUOTE_AMOUNT_USD
    ).trim(),
    quoteSummary: String(
      env.CLAWZ_AGENT_QUOTE_SUMMARY ??
        "Quote returned by the OpenClaw public hire ingress after estimating this request."
    ).trim(),
    quoteExpiresInSeconds: parsePositiveInteger(env.CLAWZ_AGENT_QUOTE_EXPIRES_IN_SECONDS, 15 * 60),
    internalHireUrl: String(env.OPENCLAW_INTERNAL_HIRE_URL ?? "").trim(),
    auditLog: String(env.CLAWZ_AGENT_AUDIT_LOG ?? "").trim(),
    maxBodyBytes: parsePositiveInteger(env.CLAWZ_AGENT_MAX_BODY_BYTES, DEFAULT_MAX_BODY_BYTES),
    maxTimestampAgeMs: parsePositiveInteger(env.CLAWZ_AGENT_MAX_TIMESTAMP_AGE_MS, DEFAULT_MAX_TIMESTAMP_AGE_MS),
    replayTtlMs: parsePositiveInteger(env.CLAWZ_AGENT_REPLAY_TTL_MS, DEFAULT_REPLAY_TTL_MS),
    rateLimitPerMinute: parsePositiveInteger(env.CLAWZ_AGENT_RATE_LIMIT_PER_MINUTE, DEFAULT_RATE_LIMIT_PER_MINUTE),
    demoCompletePaidExecution: String(env.CLAWZ_AGENT_DEMO_COMPLETE_PAID_EXECUTION ?? "").toLowerCase() === "true"
  };
}

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function sha256Hex(value) {
  return createHash("sha256").update(value).digest("hex");
}

function safeEqual(left, right) {
  const leftBuffer = Buffer.from(left);
  const rightBuffer = Buffer.from(right);
  return leftBuffer.length === rightBuffer.length && timingSafeEqual(leftBuffer, rightBuffer);
}

function jsonResponse(response, statusCode, payload) {
  response.writeHead(statusCode, {
    "content-type": "application/json",
    "cache-control": "no-store"
  });
  response.end(JSON.stringify(payload));
}

function publicError(response, statusCode, message) {
  jsonResponse(response, statusCode, {
    error: message
  });
}

function readRequestBody(request, maxBytes) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let totalBytes = 0;
    request.on("data", (chunk) => {
      totalBytes += chunk.length;
      if (totalBytes > maxBytes) {
        reject(new Error("request body too large"));
        request.destroy();
        return;
      }
      chunks.push(chunk);
    });
    request.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    request.on("error", reject);
  });
}

function evictReplayEntries(config) {
  const now = Date.now();
  for (const [requestId, seenAtMs] of replayCache.entries()) {
    if (now - seenAtMs > config.replayTtlMs) {
      replayCache.delete(requestId);
    }
  }
}

function assertNotReplayed(config, requestId) {
  evictReplayEntries(config);
  if (replayCache.has(requestId)) {
    throw Object.assign(new Error("duplicate request id"), { statusCode: 409 });
  }
  replayCache.set(requestId, Date.now());
}

function assertRateLimit(config, request) {
  const limit = config.rateLimitPerMinute;
  if (limit <= 0) {
    return;
  }
  const key = request.socket.remoteAddress ?? "unknown";
  const now = Date.now();
  const bucket = rateLimitBuckets.get(key);
  if (!bucket || now - bucket.startedAtMs >= 60_000) {
    rateLimitBuckets.set(key, { startedAtMs: now, count: 1 });
    return;
  }
  bucket.count += 1;
  if (bucket.count > limit) {
    throw Object.assign(new Error("rate limit exceeded"), { statusCode: 429 });
  }
}

function assertSignedSantaClawzRequest(config, request, body) {
  if (!config.ingressToken || !config.signingSecret) {
    throw Object.assign(new Error("ingress credentials not configured"), { statusCode: 503 });
  }

  const authorization = request.headers.authorization;
  if (authorization !== `Bearer ${config.ingressToken}`) {
    throw Object.assign(new Error("unauthorized"), { statusCode: 401 });
  }

  const requestId = request.headers["x-santaclawz-request-id"];
  const timestamp = request.headers["x-santaclawz-timestamp"];
  const bodyDigest = request.headers["x-santaclawz-body-sha256"];
  const signature = request.headers["x-santaclawz-signature"];
  if (
    typeof requestId !== "string" ||
    typeof timestamp !== "string" ||
    typeof bodyDigest !== "string" ||
    typeof signature !== "string"
  ) {
    throw Object.assign(new Error("missing SantaClawz signature headers"), { statusCode: 401 });
  }

  const timestampMs = Date.parse(timestamp);
  if (!Number.isFinite(timestampMs) || Math.abs(Date.now() - timestampMs) > config.maxTimestampAgeMs) {
    throw Object.assign(new Error("stale SantaClawz request"), { statusCode: 401 });
  }

  const expectedDigest = sha256Hex(body);
  if (!safeEqual(bodyDigest, expectedDigest)) {
    throw Object.assign(new Error("body digest mismatch"), { statusCode: 401 });
  }

  const expectedSignature = `v1=${createHmac("sha256", config.signingSecret)
    .update(`${timestamp}.${requestId}.${expectedDigest}`)
    .digest("hex")}`;
  if (!safeEqual(signature, expectedSignature)) {
    throw Object.assign(new Error("invalid SantaClawz signature"), { statusCode: 401 });
  }

  assertNotReplayed(config, requestId);
  return requestId;
}

function quoteReturnPackage(config, requestId) {
  if (!/^[0-9]+(\.[0-9]{1,6})?$/.test(config.quoteAmountUsd)) {
    throw Object.assign(new Error("quote amount is misconfigured"), { statusCode: 500 });
  }
  return {
    schema_version: "santaclawz-return/1.0",
    request_id: requestId,
    status: "quoted",
    agent_private: true,
    quote: {
      amount_usd: config.quoteAmountUsd,
      currency: "USDC",
      expires_at_iso: new Date(Date.now() + config.quoteExpiresInSeconds * 1000).toISOString(),
      summary: config.quoteSummary.slice(0, 1000)
    }
  };
}

function completedDemoPackage(requestId, body) {
  return {
    schema_version: "santaclawz-return/1.0",
    request_id: requestId,
    status: "completed",
    agent_private: true,
    verified_output: {
      package_hash: sha256Hex(body),
      hash_algorithm: "sha256",
      verification_manifest: {
        mode: "demo",
        note: "Template demo completion. Replace with a real OpenClaw verified output package."
      },
      deliverables: []
    }
  };
}

function appendAudit(config, event) {
  if (!config.auditLog) {
    return;
  }
  const auditPath = path.resolve(config.auditLog);
  mkdirSync(path.dirname(auditPath), { recursive: true });
  appendFileSync(auditPath, `${JSON.stringify({ at: new Date().toISOString(), ...event })}\n`, { mode: 0o600 });
}

async function forwardToInternalRuntime(config, body, request) {
  if (!config.internalHireUrl) {
    return null;
  }
  const response = await fetch(config.internalHireUrl, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-santaclawz-request-id": String(request.headers["x-santaclawz-request-id"] ?? "")
    },
    body,
    signal: AbortSignal.timeout(30_000)
  });
  const text = await response.text();
  return {
    statusCode: response.status,
    text
  };
}

async function handleHire(request, response, args) {
  const config = loadConfig(args);
  try {
    assertRateLimit(config, request);
    const body = await readRequestBody(request, config.maxBodyBytes);
    const requestId = assertSignedSantaClawzRequest(config, request, body);
    const payload = JSON.parse(body);
    if (!isRecord(payload) || payload.schema_version !== "santaclawz-request/1.0") {
      throw Object.assign(new Error("bad SantaClawz request schema"), { statusCode: 400 });
    }

    const requestKind = payload.request_kind;
    if (requestKind === "quote") {
      const quote = quoteReturnPackage(config, requestId);
      appendAudit(config, { type: "quote-returned", requestId, quoteAmountUsd: quote.quote.amount_usd });
      jsonResponse(response, 200, quote);
      return;
    }

    if (requestKind !== "paid-execution") {
      throw Object.assign(new Error("unsupported request kind"), { statusCode: 400 });
    }
    const payment = isRecord(payload.payment) ? payload.payment : {};
    const paymentStatus = payment.status;
    if (!payload.paid_or_escrowed || !["settled", "paid", "escrowed"].includes(String(paymentStatus))) {
      throw Object.assign(new Error("paid execution requires settled payment or escrow"), { statusCode: 402 });
    }

    if (config.demoCompletePaidExecution) {
      const completed = completedDemoPackage(requestId, body);
      appendAudit(config, { type: "paid-execution-completed", requestId, digest: completed.verified_output.package_hash });
      jsonResponse(response, 200, completed);
      return;
    }

    const forwarded = await forwardToInternalRuntime(config, body, request);
    if (forwarded) {
      response.writeHead(forwarded.statusCode, {
        "content-type": "application/json",
        "cache-control": "no-store"
      });
      response.end(forwarded.text);
      appendAudit(config, { type: "paid-execution-forwarded", requestId, statusCode: forwarded.statusCode });
      return;
    }

    appendAudit(config, { type: "paid-execution-accepted", requestId });
    jsonResponse(response, 202, { ok: true, requestId, accepted: true });
  } catch (error) {
    const statusCode = Number.isInteger(error?.statusCode) ? error.statusCode : 400;
    appendAudit(config, {
      type: "hire-rejected",
      statusCode,
      message: error instanceof Error ? error.message : String(error)
    });
    publicError(response, statusCode, error instanceof Error ? error.message : "hire request rejected");
  }
}

function handleChallenge(response, config) {
  if (!config.challengeFile || !existsSync(config.challengeFile)) {
    publicError(response, 404, "ownership challenge not installed yet");
    return;
  }
  response.writeHead(200, {
    "content-type": "application/json",
    "cache-control": "no-store"
  });
  response.end(readFileSync(config.challengeFile, "utf8"));
}

const args = parseArgs(process.argv.slice(2));
if (args.help) {
  printUsage();
  process.exit(0);
}

const host = String(args.host ?? process.env.HOST ?? DEFAULT_HOST);
const port = parsePositiveInteger(args.port ?? process.env.PORT, DEFAULT_PORT);

const server = createServer((request, response) => {
  const url = new URL(request.url ?? "/", `http://${request.headers.host ?? "127.0.0.1"}`);
  const config = loadConfig(args);
  if (request.method === "GET" && url.pathname === "/") {
    jsonResponse(response, 200, {
      ok: true,
      service: "santaclawz-openclaw-public-hire-ingress"
    });
    return;
  }
  if (request.method === "GET" && url.pathname === "/health") {
    jsonResponse(response, 200, {
      ok: true,
      service: "santaclawz-openclaw-public-hire-ingress",
      credentialsConfigured: Boolean(config.ingressToken && config.signingSecret),
      challengeInstalled: Boolean(config.challengeFile && existsSync(config.challengeFile))
    });
    return;
  }
  if (request.method === "GET" && url.pathname === CHALLENGE_PATH) {
    handleChallenge(response, config);
    return;
  }
  if (request.method === "POST" && url.pathname === "/hire") {
    void handleHire(request, response, args);
    return;
  }
  publicError(response, 404, "not found");
});

server.listen(port, host, () => {
  console.error(`SantaClawz public hire ingress listening on http://${host}:${port}`);
});
