#!/usr/bin/env node
import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from "node:fs";
import { createServer } from "node:http";
import path from "node:path";

const DEFAULT_HOST = "127.0.0.1";
const DEFAULT_PORT = 8797;
const DEFAULT_MAX_BODY_BYTES = 64 * 1024;
const DEFAULT_MAX_TIMESTAMP_AGE_MS = 5 * 60 * 1000;
const DEFAULT_REPLAY_TTL_MS = 10 * 60 * 1000;
const DEFAULT_RATE_LIMIT_PER_MINUTE = 60;
const DEFAULT_QUOTE_AMOUNT_USD = "0.20";
const CHALLENGE_PATH = "/.well-known/santaclawz-agent-challenge.json";
const SERVICE_KEY_PATTERN = /^[a-z0-9][a-z0-9_:-]{0,79}$/;

const replayCache = new Map();
const rateLimitBuckets = new Map();

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === "--") {
      continue;
    }
    if (!token.startsWith("--")) {
      continue;
    }
    const key = token.slice(2);
    if (key === "help") {
      args[key] = true;
      continue;
    }
    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      throw new Error(`Missing value for --${key}`);
    }
    args[key] = value;
    index += 1;
  }
  return args;
}

function printUsage() {
  console.error(`Usage:
  node starters/openclaw-public-hire-ingress/server.mjs \\
    [--agent-env-file .env.santaclawz] \\
    [--agent-env-dir .santaclawz-agents] \\
    [--challenge-file .well-known/santaclawz-agent-challenge.json] \\
    [--host 127.0.0.1] \\
    [--port 8797]

Important env vars:
  CLAWZ_AGENT_INGRESS_TOKEN      Bearer token generated by SantaClawz enrollment.
  CLAWZ_AGENT_SIGNING_SECRET     HMAC key generated by SantaClawz enrollment.
  CLAWZ_AGENT_SERVICE_KEY        Active service key this ingress accepts for the agent.
  CLAWZ_AGENT_ENV_DIR            Optional directory of per-agent .env.santaclawz files.
  CLAWZ_AGENT_QUOTE_AMOUNT_USD   Optional exact quote amount returned for quote intake.
  OPENCLAW_INTERNAL_HIRE_URL     Optional private runtime URL for paid execution.
`);
}

function unquoteEnvValue(value) {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function readEnvFile(filePath) {
  if (!filePath || !existsSync(filePath)) {
    return {};
  }
  const env = {};
  for (const rawLine of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const separatorIndex = line.indexOf("=");
    if (separatorIndex <= 0) {
      continue;
    }
    env[line.slice(0, separatorIndex).trim()] = unquoteEnvValue(line.slice(separatorIndex + 1));
  }
  return env;
}

function parsePositiveInteger(value, fallback) {
  const parsed = Number.parseInt(String(value ?? ""), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function resolvePath(value, fallback) {
  const candidate = String(value ?? fallback ?? "").trim();
  return candidate ? path.resolve(candidate) : "";
}

function normalizeServiceKey(value) {
  const normalized = String(value ?? "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return normalized || "agent";
}

function collectAgentEnvFiles(args) {
  const files = [];
  const explicitFile = resolvePath(args["agent-env-file"] ?? args["env-file"] ?? process.env.CLAWZ_AGENT_ENV_FILE, "");
  if (explicitFile) {
    files.push(explicitFile);
  }

  const envDir = resolvePath(args["agent-env-dir"] ?? process.env.CLAWZ_AGENT_ENV_DIR, "");
  if (envDir && existsSync(envDir)) {
    for (const entry of readdirSync(envDir, { withFileTypes: true })) {
      if (entry.isFile()) {
        files.push(path.join(envDir, entry.name));
      }
    }
  }

  return [...new Set(files)];
}

function isServiceActive(value) {
  const normalized = String(value ?? "true").trim().toLowerCase();
  return !["0", "false", "off", "paused", "disabled", "inactive"].includes(normalized);
}

function buildEnrollmentFromEnv(env, source) {
  const ingressToken = String(env.CLAWZ_AGENT_INGRESS_TOKEN ?? "").trim();
  const signingSecret = String(env.CLAWZ_AGENT_SIGNING_SECRET ?? "").trim();
  if (!ingressToken || !signingSecret) {
    return null;
  }

  return {
    source,
    agentId: String(env.CLAWZ_AGENT_ID ?? "").trim(),
    sessionId: String(env.CLAWZ_AGENT_SESSION_ID ?? "").trim(),
    serviceKey: normalizeServiceKey(env.CLAWZ_AGENT_SERVICE_KEY ?? env.CLAWZ_AGENT_SERVICE ?? env.CLAWZ_AGENT_ID),
    active: isServiceActive(env.CLAWZ_AGENT_ACTIVE ?? env.CLAWZ_AGENT_SERVICE_ACTIVE),
    ingressToken,
    signingSecret,
    quoteAmountUsd: String(
      env.CLAWZ_AGENT_QUOTE_AMOUNT_USD ??
        env.CLAWZ_AGENT_REFERENCE_PRICE_USD ??
        DEFAULT_QUOTE_AMOUNT_USD
    ).trim(),
    quoteSummary: String(
      env.CLAWZ_AGENT_QUOTE_SUMMARY ??
        "Quote returned by the OpenClaw public hire ingress after estimating this request."
    ).trim(),
    quoteExpiresInSeconds: parsePositiveInteger(env.CLAWZ_AGENT_QUOTE_EXPIRES_IN_SECONDS, 15 * 60),
    internalHireUrl: String(env.OPENCLAW_INTERNAL_HIRE_URL ?? "").trim(),
    demoCompletePaidExecution: String(env.CLAWZ_AGENT_DEMO_COMPLETE_PAID_EXECUTION ?? "").toLowerCase() === "true",
    demoCompleteFreeTest: String(env.CLAWZ_AGENT_DEMO_COMPLETE_FREE_TEST ?? "").toLowerCase() === "true"
  };
}

function dedupeEnrollments(enrollments) {
  const seen = new Set();
  const deduped = [];
  for (const enrollment of enrollments) {
    const key = `${enrollment.ingressToken}:${enrollment.serviceKey}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    deduped.push(enrollment);
  }
  return deduped;
}

function loadConfig(args) {
  const envFiles = collectAgentEnvFiles(args);
  const envFile = envFiles[0] ?? "";
  const fileEnv = readEnvFile(envFile);
  const env = {
    ...process.env,
    ...fileEnv
  };
  const fileEnrollments = envFiles
    .map((file) => buildEnrollmentFromEnv({ ...process.env, ...readEnvFile(file) }, file))
    .filter(Boolean);
  const processEnrollment = buildEnrollmentFromEnv(process.env, "process.env");
  const challengeFile = resolvePath(
    args["challenge-file"] ?? env.CLAWZ_AGENT_OWNERSHIP_CHALLENGE_FILE,
    ".well-known/santaclawz-agent-challenge.json"
  );
  return {
    envFile,
    envFiles,
    challengeFile,
    enrollments: dedupeEnrollments([...fileEnrollments, ...(processEnrollment ? [processEnrollment] : [])]),
    quoteAmountUsd: String(
      env.CLAWZ_AGENT_QUOTE_AMOUNT_USD ??
        env.CLAWZ_AGENT_REFERENCE_PRICE_USD ??
        DEFAULT_QUOTE_AMOUNT_USD
    ).trim(),
    quoteSummary: String(
      env.CLAWZ_AGENT_QUOTE_SUMMARY ??
        "Quote returned by the OpenClaw public hire ingress after estimating this request."
    ).trim(),
    quoteExpiresInSeconds: parsePositiveInteger(env.CLAWZ_AGENT_QUOTE_EXPIRES_IN_SECONDS, 15 * 60),
    internalHireUrl: String(env.OPENCLAW_INTERNAL_HIRE_URL ?? "").trim(),
    auditLog: String(env.CLAWZ_AGENT_AUDIT_LOG ?? "").trim(),
    maxBodyBytes: parsePositiveInteger(env.CLAWZ_AGENT_MAX_BODY_BYTES, DEFAULT_MAX_BODY_BYTES),
    maxTimestampAgeMs: parsePositiveInteger(env.CLAWZ_AGENT_MAX_TIMESTAMP_AGE_MS, DEFAULT_MAX_TIMESTAMP_AGE_MS),
    replayTtlMs: parsePositiveInteger(env.CLAWZ_AGENT_REPLAY_TTL_MS, DEFAULT_REPLAY_TTL_MS),
    rateLimitPerMinute: parsePositiveInteger(env.CLAWZ_AGENT_RATE_LIMIT_PER_MINUTE, DEFAULT_RATE_LIMIT_PER_MINUTE),
    demoCompletePaidExecution: String(env.CLAWZ_AGENT_DEMO_COMPLETE_PAID_EXECUTION ?? "").toLowerCase() === "true",
    demoCompleteFreeTest: String(env.CLAWZ_AGENT_DEMO_COMPLETE_FREE_TEST ?? "").toLowerCase() === "true"
  };
}

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function sha256Hex(value) {
  return createHash("sha256").update(value).digest("hex");
}

function safeEqual(left, right) {
  const leftBuffer = Buffer.from(left);
  const rightBuffer = Buffer.from(right);
  return leftBuffer.length === rightBuffer.length && timingSafeEqual(leftBuffer, rightBuffer);
}

function jsonResponse(response, statusCode, payload) {
  response.writeHead(statusCode, {
    "content-type": "application/json",
    "cache-control": "no-store"
  });
  response.end(JSON.stringify(payload));
}

function publicError(response, statusCode, message) {
  jsonResponse(response, statusCode, {
    error: message
  });
}

function safePublicHireError(statusCode) {
  if (statusCode === 401) {
    return "unauthorized SantaClawz request";
  }
  if (statusCode === 402) {
    return "payment authorization required";
  }
  if (statusCode === 403) {
    return "service is not accepting this request";
  }
  if (statusCode === 413) {
    return "request body is too large";
  }
  if (statusCode === 503) {
    return "agent ingress is not ready";
  }
  return "hire request rejected";
}

function readRequestBody(request, maxBytes) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let totalBytes = 0;
    request.on("data", (chunk) => {
      totalBytes += chunk.length;
      if (totalBytes > maxBytes) {
        reject(new Error("request body too large"));
        request.destroy();
        return;
      }
      chunks.push(chunk);
    });
    request.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    request.on("error", reject);
  });
}

function evictReplayEntries(config) {
  const now = Date.now();
  for (const [requestId, seenAtMs] of replayCache.entries()) {
    if (now - seenAtMs > config.replayTtlMs) {
      replayCache.delete(requestId);
    }
  }
}

function assertNotReplayed(config, requestId) {
  evictReplayEntries(config);
  if (replayCache.has(requestId)) {
    throw Object.assign(new Error("duplicate request id"), { statusCode: 409 });
  }
  replayCache.set(requestId, Date.now());
}

function assertRateLimit(config, request) {
  const limit = config.rateLimitPerMinute;
  if (limit <= 0) {
    return;
  }
  const key = request.socket.remoteAddress ?? "unknown";
  const now = Date.now();
  const bucket = rateLimitBuckets.get(key);
  if (!bucket || now - bucket.startedAtMs >= 60_000) {
    rateLimitBuckets.set(key, { startedAtMs: now, count: 1 });
    return;
  }
  bucket.count += 1;
  if (bucket.count > limit) {
    throw Object.assign(new Error("rate limit exceeded"), { statusCode: 429 });
  }
}

function assertSignedSantaClawzRequest(config, request, body) {
  if (config.enrollments.length === 0) {
    throw Object.assign(new Error("ingress credentials not configured"), { statusCode: 503 });
  }

  const authorization = request.headers.authorization;
  const enrollment = config.enrollments.find((candidate) => authorization === `Bearer ${candidate.ingressToken}`);
  if (!enrollment) {
    throw Object.assign(new Error("unauthorized"), { statusCode: 401 });
  }

  const requestId = request.headers["x-santaclawz-request-id"];
  const timestamp = request.headers["x-santaclawz-timestamp"];
  const bodyDigest = request.headers["x-santaclawz-body-sha256"];
  const signature = request.headers["x-santaclawz-signature"];
  if (
    typeof requestId !== "string" ||
    typeof timestamp !== "string" ||
    typeof bodyDigest !== "string" ||
    typeof signature !== "string"
  ) {
    throw Object.assign(new Error("missing SantaClawz signature headers"), { statusCode: 401 });
  }

  const timestampMs = Date.parse(timestamp);
  if (!Number.isFinite(timestampMs) || Math.abs(Date.now() - timestampMs) > config.maxTimestampAgeMs) {
    throw Object.assign(new Error("stale SantaClawz request"), { statusCode: 401 });
  }

  const expectedDigest = sha256Hex(body);
  if (!safeEqual(bodyDigest, expectedDigest)) {
    throw Object.assign(new Error("body digest mismatch"), { statusCode: 401 });
  }

  const expectedSignature = `v1=${createHmac("sha256", enrollment.signingSecret)
    .update(`${timestamp}.${requestId}.${expectedDigest}`)
    .digest("hex")}`;
  if (!safeEqual(signature, expectedSignature)) {
    throw Object.assign(new Error("invalid SantaClawz signature"), { statusCode: 401 });
  }

  assertNotReplayed(config, requestId);
  return { requestId, enrollment };
}

function assertActiveService(enrollment, payload) {
  const payloadServiceKey = normalizeServiceKey(payload.service_key ?? payload.service);
  if (!payload.service_key || !SERVICE_KEY_PATTERN.test(String(payload.service_key)) || payload.service !== payload.service_key) {
    throw Object.assign(new Error("service_key must be present and match service"), { statusCode: 400 });
  }
  if (payloadServiceKey !== enrollment.serviceKey) {
    throw Object.assign(new Error(`service is not active on this ingress: ${payloadServiceKey}`), { statusCode: 403 });
  }
  if (!enrollment.active) {
    throw Object.assign(new Error(`service is paused on this ingress: ${payloadServiceKey}`), { statusCode: 403 });
  }
}

function assertHirePolicy(payload) {
  const requestType = payload.request_type;
  const pricingMode = payload.pricing_mode;
  const paymentStatus = payload.payment_status;
  const payment = isRecord(payload.payment) ? payload.payment : {};
  if (!["quote_intake", "paid_execution", "free_test"].includes(String(requestType))) {
    throw Object.assign(new Error("unsupported request_type"), { statusCode: 400 });
  }
  if (!["quote-required", "fixed-exact", "free-test"].includes(String(pricingMode))) {
    throw Object.assign(new Error("unsupported pricing_mode"), { statusCode: 400 });
  }
  if (payment.status !== paymentStatus) {
    throw Object.assign(new Error("payment.status must match payment_status"), { statusCode: 400 });
  }

  if (requestType === "quote_intake") {
    if (pricingMode !== "quote-required" || paymentStatus !== "quote_requested" || payload.paid_or_escrowed !== false) {
      throw Object.assign(new Error("quote_intake policy mismatch"), { statusCode: 400 });
    }
    if (payload.settled_amount_usd !== undefined) {
      throw Object.assign(new Error("quote_intake must not include settled_amount_usd"), { statusCode: 400 });
    }
    return requestType;
  }

  if (requestType === "free_test") {
    if (pricingMode !== "free-test" || paymentStatus !== "free_test" || payload.paid_or_escrowed !== false) {
      throw Object.assign(new Error("free_test policy mismatch"), { statusCode: 400 });
    }
    if (payload.settled_amount_usd !== undefined || payload.payment?.rail || payload.payment?.amount_usd) {
      throw Object.assign(new Error("free_test must not include paid settlement fields"), { statusCode: 400 });
    }
    return requestType;
  }

  if (!["fixed-exact", "quote-required"].includes(String(pricingMode)) || !["settled", "paid", "escrowed"].includes(String(paymentStatus))) {
    throw Object.assign(new Error("paid_execution policy mismatch"), { statusCode: 400 });
  }
  if (!payload.paid_or_escrowed || !/^[0-9]+(\.[0-9]{1,6})?$/.test(String(payload.settled_amount_usd ?? ""))) {
    throw Object.assign(new Error("paid_execution requires settled_amount_usd"), { statusCode: 402 });
  }
  if (!isRecord(payment) || payment.amount_usd !== payload.settled_amount_usd || !payment.rail) {
    throw Object.assign(new Error("payment object must match paid_execution policy fields"), { statusCode: 402 });
  }
  return requestType;
}

function quoteReturnPackage(config, requestId, enrollment) {
  const quoteAmountUsd = enrollment.quoteAmountUsd || config.quoteAmountUsd;
  const quoteExpiresInSeconds = enrollment.quoteExpiresInSeconds || config.quoteExpiresInSeconds;
  const quoteSummary = enrollment.quoteSummary || config.quoteSummary;
  if (!/^[0-9]+(\.[0-9]{1,6})?$/.test(quoteAmountUsd)) {
    throw Object.assign(new Error("quote amount is misconfigured"), { statusCode: 500 });
  }
  return {
    schema_version: "santaclawz-return/1.0",
    request_id: requestId,
    status: "quoted",
    agent_private: true,
    quote: {
      amount_usd: quoteAmountUsd,
      currency: "USDC",
      expires_at_iso: new Date(Date.now() + quoteExpiresInSeconds * 1000).toISOString(),
      summary: quoteSummary.slice(0, 1000)
    }
  };
}

function completedDemoPackage(requestId, body, mode = "paid_execution") {
  return {
    schema_version: "santaclawz-return/1.0",
    request_id: requestId,
    status: "completed",
    agent_private: true,
    execution_mode: "demo-complete",
    real_work_executed: false,
    buyer_visible: false,
    marketplace_completion_credit: false,
    verified_output: {
      package_hash: sha256Hex(body),
      hash_algorithm: "sha256",
      verification_manifest: {
        mode: "demo",
        input_digest_sha256: sha256Hex(body),
        checks_performed: [
          "santaclawz_signature_verified",
          "request_id_replay_checked",
          "service_key_matched",
          mode === "free_test" ? "free_test_policy_verified" : "paid_execution_policy_verified"
        ],
        files_produced: [],
        blocked_suspicious_instructions: [],
        note: "Template demo completion. Replace with a real OpenClaw verified output package."
      },
      deliverables: []
    }
  };
}

function appendAudit(config, event) {
  if (!config.auditLog) {
    return;
  }
  const auditPath = path.resolve(config.auditLog);
  mkdirSync(path.dirname(auditPath), { recursive: true });
  appendFileSync(auditPath, `${JSON.stringify({ at: new Date().toISOString(), ...event })}\n`, { mode: 0o600 });
}

async function forwardToInternalRuntime(config, body, request, enrollment) {
  const internalHireUrl = enrollment.internalHireUrl || config.internalHireUrl;
  if (!internalHireUrl) {
    return null;
  }
  const response = await fetch(internalHireUrl, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-santaclawz-request-id": String(request.headers["x-santaclawz-request-id"] ?? "")
    },
    body,
    signal: AbortSignal.timeout(30_000)
  });
  const text = await response.text();
  return {
    statusCode: response.status,
    text
  };
}

async function handleHire(request, response, args) {
  const config = loadConfig(args);
  try {
    assertRateLimit(config, request);
    const body = await readRequestBody(request, config.maxBodyBytes);
    const { requestId, enrollment } = assertSignedSantaClawzRequest(config, request, body);
    const payload = JSON.parse(body);
    if (!isRecord(payload) || payload.schema_version !== "santaclawz-request/1.0") {
      throw Object.assign(new Error("bad SantaClawz request schema"), { statusCode: 400 });
    }

    assertActiveService(enrollment, payload);
    const requestType = assertHirePolicy(payload);
    if (requestType === "quote_intake") {
      const quote = quoteReturnPackage(config, requestId, enrollment);
      appendAudit(config, { type: "quote-returned", requestId, serviceKey: enrollment.serviceKey, quoteAmountUsd: quote.quote.amount_usd });
      jsonResponse(response, 200, quote);
      return;
    }

    if (requestType === "free_test") {
      if (enrollment.demoCompleteFreeTest || config.demoCompleteFreeTest) {
        const completed = completedDemoPackage(requestId, body, "free_test");
        appendAudit(config, { type: "free-test-completed", requestId, serviceKey: enrollment.serviceKey, digest: completed.verified_output.package_hash });
        jsonResponse(response, 200, completed);
        return;
      }

      const forwarded = await forwardToInternalRuntime(config, body, request, enrollment);
      if (forwarded) {
        response.writeHead(forwarded.statusCode, {
          "content-type": "application/json",
          "cache-control": "no-store"
        });
        response.end(forwarded.text);
        appendAudit(config, { type: "free-test-forwarded", requestId, serviceKey: enrollment.serviceKey, statusCode: forwarded.statusCode });
        return;
      }

      appendAudit(config, { type: "free-test-accepted", requestId, serviceKey: enrollment.serviceKey });
      jsonResponse(response, 202, { ok: true, accepted: true, request_id: requestId, request_type: "free_test" });
      return;
    }

    if (!payload.paid_or_escrowed || !["settled", "paid", "escrowed"].includes(String(payload.payment_status))) {
      throw Object.assign(new Error("paid execution requires settled payment or escrow"), { statusCode: 402 });
    }

    if (enrollment.demoCompletePaidExecution || config.demoCompletePaidExecution) {
      const completed = completedDemoPackage(requestId, body);
      appendAudit(config, { type: "paid-execution-completed", requestId, serviceKey: enrollment.serviceKey, digest: completed.verified_output.package_hash });
      jsonResponse(response, 200, completed);
      return;
    }

    const forwarded = await forwardToInternalRuntime(config, body, request, enrollment);
    if (forwarded) {
      response.writeHead(forwarded.statusCode, {
        "content-type": "application/json",
        "cache-control": "no-store"
      });
      response.end(forwarded.text);
      appendAudit(config, { type: "paid-execution-forwarded", requestId, serviceKey: enrollment.serviceKey, statusCode: forwarded.statusCode });
      return;
    }

    appendAudit(config, { type: "paid-execution-accepted", requestId, serviceKey: enrollment.serviceKey });
    jsonResponse(response, 202, { ok: true, requestId, accepted: true });
  } catch (error) {
    const statusCode = Number.isInteger(error?.statusCode) ? error.statusCode : 400;
    appendAudit(config, {
      type: "hire-rejected",
      statusCode,
      message: error instanceof Error ? error.message : String(error)
    });
    publicError(response, statusCode, safePublicHireError(statusCode));
  }
}

function handleChallenge(response, config) {
  if (!config.challengeFile || !existsSync(config.challengeFile)) {
    publicError(response, 404, "ownership challenge not installed yet");
    return;
  }
  response.writeHead(200, {
    "content-type": "application/json",
    "cache-control": "no-store"
  });
  response.end(readFileSync(config.challengeFile, "utf8"));
}

function publicDescriptor(config) {
  return {
    ok: true,
    service: "santaclawz-openclaw-public-hire-ingress",
    credentialsConfigured: config.enrollments.length > 0,
    activeServices: config.enrollments.filter((enrollment) => enrollment.active).map((enrollment) => enrollment.serviceKey),
    publicSurface: [
      "GET /health",
      "GET /.well-known/santaclawz-agent-challenge.json",
      "POST /hire",
      "POST /:service/hire"
    ]
  };
}

function isHirePostPath(pathname) {
  return pathname === "/hire" || pathname.endsWith("/hire");
}

const args = parseArgs(process.argv.slice(2));
if (args.help) {
  printUsage();
  process.exit(0);
}

const host = String(args.host ?? process.env.HOST ?? DEFAULT_HOST);
const port = parsePositiveInteger(args.port ?? process.env.PORT, DEFAULT_PORT);

const server = createServer((request, response) => {
  const url = new URL(request.url ?? "/", `http://${request.headers.host ?? "127.0.0.1"}`);
  const config = loadConfig(args);
  if (request.method === "GET" && url.pathname === "/health") {
    jsonResponse(response, 200, {
      ...publicDescriptor(config),
      challengeInstalled: Boolean(config.challengeFile && existsSync(config.challengeFile))
    });
    return;
  }
  if (request.method === "GET" && url.pathname === CHALLENGE_PATH) {
    handleChallenge(response, config);
    return;
  }
  if (request.method === "GET") {
    jsonResponse(response, 200, publicDescriptor(config));
    return;
  }
  if (request.method === "POST" && isHirePostPath(url.pathname)) {
    void handleHire(request, response, args);
    return;
  }
  publicError(response, 404, "not found");
});

server.listen(port, host, () => {
  console.error(`SantaClawz public hire ingress listening on http://${host}:${port}`);
});
