import type { ApprovalLeaf, CapabilityLeaf, DisclosureLeaf, OriginProofLeaf, SessionHeaderLeaf, TurnHeaderLeaf } from "../leaves/types.js";
import type { ZkTlsOriginProof } from "../interop/agent-proof.js";
import { type CapabilityManifest } from "../manifests/capability-manifest.js";
import type { PrivacyException, PrivacyMode } from "../privacy/types.js";
import type { ToolReceipt, OutputCommitment } from "../receipts/tool-receipt.js";
import type { RetentionPolicy } from "../retention/types.js";
export declare const samplePrivacyMode: PrivacyMode;
export declare const sampleRetentionPolicy: RetentionPolicy;
export declare const sampleCapabilityManifest: CapabilityManifest;
export declare const sampleCapabilityLeaf: CapabilityLeaf;
export declare const sampleSessionHeaderLeaf: SessionHeaderLeaf;
export declare const sampleTurnHeaderLeaf: TurnHeaderLeaf;
export declare const sampleApprovalLeaf: ApprovalLeaf;
export declare const sampleDisclosureLeaf: DisclosureLeaf;
export declare const sampleOriginProof: ZkTlsOriginProof;
export declare const sampleOriginProofLeaf: OriginProofLeaf;
export declare const samplePrivacyException: PrivacyException;
export declare const sampleToolReceipt: ToolReceipt;
export declare const sampleOutputCommitment: OutputCommitment;
export declare const GOLDEN_VECTORS: {
    capabilityManifest: import("../leaves/builders.js").CanonicalLeaf<CapabilityManifest>;
    capabilityLeaf: import("../leaves/builders.js").CanonicalLeaf<CapabilityLeaf>;
    sessionHeaderLeaf: import("../leaves/builders.js").CanonicalLeaf<SessionHeaderLeaf>;
    turnHeaderLeaf: import("../leaves/builders.js").CanonicalLeaf<TurnHeaderLeaf>;
    approvalLeaf: import("../leaves/builders.js").CanonicalLeaf<ApprovalLeaf>;
    disclosureLeaf: import("../leaves/builders.js").CanonicalLeaf<DisclosureLeaf>;
    originProof: import("../leaves/builders.js").CanonicalLeaf<ZkTlsOriginProof>;
    originProofLeaf: import("../leaves/builders.js").CanonicalLeaf<OriginProofLeaf>;
    toolReceipt: import("../leaves/builders.js").CanonicalLeaf<ToolReceipt>;
    outputCommitment: import("../leaves/builders.js").CanonicalLeaf<OutputCommitment>;
    privacyMode: import("../leaves/builders.js").CanonicalLeaf<PrivacyMode>;
    retentionPolicy: import("../leaves/builders.js").CanonicalLeaf<RetentionPolicy>;
    privacyException: import("../leaves/builders.js").CanonicalLeaf<PrivacyException>;
};
